from datetime import date
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"
CACHE_DIR = DATA_DIR / "cache"

DEFAULT_TICKER = "AAPL"
DEFAULT_START_DATE = date(2020, 1, 1)
DEFAULT_FORECAST_HORIZON = 7
MAX_FORECAST_HORIZON = 30

TEST_SIZE = 0.2
RANDOM_STATE = 42

SMA_WINDOW = 20
EMA_SPAN = 20
RSI_WINDOW = 14
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9

BASELINE_WINDOW = 10

LSTM_SEQUENCE_LENGTH = 60
LSTM_EPOCHS = 12
LSTM_BATCH_SIZE = 32
LSTM_UNITS = 50
LSTM_TIMEOUT_SECONDS = 240
